// Testes da Área do Cliente: capa por projeto, materiais publicados, orçamentos e comparativo,
// aprovações pelo cliente e registro pelo escritório, versões, histórico e isolamento entre clientes.
//   node scripts/test-portal.js
process.env.TZ = 'America/Campo_Grande';
const fs = require('fs'); const os = require('os'); const path = require('path');
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'cnij-portal-'));
process.env.DB_FILE = path.join(tmp, 'test.sqlite'); process.env.BACKUP_DIR = path.join(tmp, 'bk'); process.env.UPLOAD_DIR = path.join(tmp, 'up');
const origLog = console.log; console.log = (...a) => { if (!String(a[0]).includes('e-mail não enviado')) origLog(...a); };
const app = require('../server');
const { get } = require('../server/db');
const client = require('./client');
const pad = (n) => String(n).padStart(2, '0');
const D = (o) => { const d = new Date(); d.setDate(d.getDate() + o); return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`; };
let pass = 0; let failN = 0;
const ok = (c, m) => { if (c) { pass++; origLog('  ✓', m); } else { failN++; origLog('  ✗', m); } };
const rejects = async (p, st, m) => { try { await p; ok(false, m + ' (deveria falhar)'); } catch (e) { ok(!st || e.status === st, `${m} → ${e.status}`); return e; } };
const IMG = fs.readFileSync(path.join(__dirname, '..', 'public', 'img', 'socios.jpg'));

(async () => {
  const server = app.listen(0); const base = `http://127.0.0.1:${server.address().port}`;
  const A = client(base); const PW = 'Teste1234';
  await A.post('/setup', { name: 'Irineu', email: 'a@t.com', password: PW }); await A.post('/auth/login', { email: 'a@t.com', password: PW });
  await A.put('/admin/settings', { office_phone: 'Irineu: (67) 98207-7556' });
  const up = (fields, name = 'render.jpg', type = 'image/jpeg', buf = IMG) => { const fd = new FormData(); fd.append('files', new Blob([buf], { type }), name); Object.entries(fields).forEach(([k, v]) => fd.append(k, String(v))); return A.upload('/files', fd); };

  const c1 = await A.post('/r/clients', { name: 'Vinícius Teste' }); const c2 = await A.post('/r/clients', { name: 'Outro Cliente' });
  const p1 = await A.post('/r/projects', { name: 'Apartamento Sunrise', client_id: c1.id }); const p1b = await A.post('/r/projects', { name: 'Casa de Praia', client_id: c1.id });
  const p2 = await A.post('/r/projects', { name: 'Projeto Alheio', client_id: c2.id });
  await A.post('/admin/users', { name: 'Vini', email: 'v@t.com', role: 'cliente', client_id: c1.id, password: PW });
  await A.post('/admin/users', { name: 'Outro', email: 'o@t.com', role: 'cliente', client_id: c2.id, password: PW });
  const C1 = client(base); await C1.post('/auth/login', { email: 'v@t.com', password: PW });
  const C2 = client(base); await C2.post('/auth/login', { email: 'o@t.com', password: PW });

  origLog('\nCapa do portal');
  let ov = await C1.get('/portal/overview'); let pp = ov.projects.find((x) => x.id === p1.id);
  ok(ov.projects.length === 2 && !pp.cover, 'cliente com dois projetos; sem capa → cartão neutro');
  ok(ov.contact.whatsapp === '5567982077556', 'contato “Fale com o escritório” vem do cadastro');
  const img1 = (await up({ project_id: p1.id, category: 'Imagens / renders' })).ids[0];
  ok(!get('SELECT client_visible FROM documents WHERE id = ?', img1).client_visible, 'upload interno não fica público automaticamente');
  await A.put(`/projects/${p1.id}/cover`, { doc_id: img1, x: 30, y: 70, zoom: 1.4 });
  const pr1 = get('SELECT * FROM projects WHERE id = ?', p1.id);
  ok(pr1.cover_doc_id === img1 && pr1.cover_x === 30 && pr1.cover_zoom === 1.4, 'capa e enquadramento salvos');
  ok(pr1.cover_display && fs.existsSync(path.join(tmp, 'up', pr1.cover_display)), 'versão otimizada gerada');
  ok(fs.readFileSync(path.join(tmp, 'up', get('SELECT file_path FROM documents WHERE id = ?', img1).file_path)).equals(IMG), 'arquivo original preservado sem cortes');
  ov = await C1.get('/portal/overview'); pp = ov.projects.find((x) => x.id === p1.id);
  ok(pp.cover && pp.cover.x === 30 && !ov.projects.find((x) => x.id === p1b.id).cover, 'capa individual por projeto');
  const cv = await C1.file(`/portal/projects/${p1.id}/cover`); ok(cv.status === 200 && /image\/jpeg/.test(cv.headers.get('content-type')), 'cliente carrega a capa do próprio projeto');
  ok((await C2.file(`/portal/projects/${p1.id}/cover`)).status === 404, 'outro cliente não acessa a capa');
  await up({ project_id: p1.id, category: 'Imagens / renders' });
  ok(get('SELECT cover_doc_id FROM projects WHERE id = ?', p1.id).cover_doc_id === img1, 'novo envio não troca a capa');
  const img2 = (await up({ project_id: p1.id, category: 'Imagens / renders' }, 'sala.jpg')).ids[0];
  await A.put(`/projects/${p1.id}/cover`, { doc_id: img2, x: 50, y: 50, zoom: 1 });
  ok(get('SELECT cover_doc_id FROM projects WHERE id = ?', p1.id).cover_doc_id === img2, 'capa trocada');
  await A.del(`/projects/${p1.id}/cover`);
  ok(!get('SELECT cover_doc_id FROM projects WHERE id = ?', p1.id).cover_doc_id && get('SELECT 1 FROM documents WHERE id = ?', img2), 'capa removida sem apagar a imagem');

  origLog('\nVeja seu projeto (materiais publicados)');
  const vid = (await up({ project_id: p1.id }, 'tour.mp4', 'video/mp4', Buffer.alloc(4096, 7))).ids[0];
  const pdf = (await up({ project_id: p1.id, category: 'Apresentações' }, 'estudo.pdf', 'application/pdf', Buffer.from('%PDF-1.4 teste'))).ids[0];
  ov = await C1.get('/portal/overview'); ok(!ov.projects.find((x) => x.id === p1.id).showcase.length, 'nada publicado antes da liberação');
  await A.put(`/documents/${img1}/showcase`, { client_visible: 1, showcase: 1, portal_title: 'Sala de estar', portal_group: 'Sala', portal_desc: 'Vista principal' });
  await A.put(`/documents/${vid}/showcase`, { client_visible: 1, showcase: 1, portal_group: 'Sala' });
  await A.put(`/documents/${pdf}/showcase`, { client_visible: 1, showcase: 1, portal_title: 'Estudo preliminar v1' });
  const pdf2 = (await up({ project_id: p1.id, category: 'Apresentações' }, 'estudo-v2.pdf', 'application/pdf', Buffer.from('%PDF-1.4 v2'))).ids[0];
  await A.put(`/documents/${pdf2}/showcase`, { client_visible: 1, showcase: 1, portal_title: 'Estudo preliminar v2' });
  await A.put(`/documents/${pdf}/showcase`, { replaced_by: pdf2 });
  await A.post(`/projects/${p1.id}/showcase-order`, { ids: [pdf2, img1, vid, pdf] });
  ov = await C1.get('/portal/overview'); pp = ov.projects.find((x) => x.id === p1.id);
  ok(pp.showcase.map((m) => m.id).join() === [pdf2, img1, vid, pdf].join(','), 'materiais publicados na ordem definida');
  ok(pp.showcase.find((m) => m.id === img1).title === 'Sala de estar' && pp.showcase.find((m) => m.id === img1).group === 'Sala', 'título e ambiente definidos pelo escritório');
  ok(pp.showcase.find((m) => m.id === pdf).previous && !pp.showcase.find((m) => m.id === pdf2).previous, 'versão anterior identificada');
  ok(pp.showcase.find((m) => m.id === vid).kind === 'video', 'vídeo publicado');
  const rr = await fetch(`${base}/api/portal/files/${vid}?inline=1`, { headers: { cookie: '' } });
  ok(rr.status === 401 || rr.status === 403, 'arquivo exige login');
  const C1f = await C1.file(`/portal/files/${vid}?inline=1`); ok(C1f.status === 200, 'cliente acessa vídeo publicado');
  const range = await C1.file(`/portal/files/${vid}?inline=1`, { Range: 'bytes=0-99' });
  ok(range.status === 206 && range.headers.get('content-range') === 'bytes 0-99/4096' && (await range.arrayBuffer()).byteLength === 100, 'vídeo responde a pedidos parciais (reprodução no navegador/iPhone)');
  await A.put(`/documents/${vid}/showcase`, { client_visible: 0 });
  ov = await C1.get('/portal/overview'); ok(!ov.projects.find((x) => x.id === p1.id).showcase.some((m) => m.id === vid) && get('SELECT 1 FROM documents WHERE id = ?', vid), 'retirado da visualização sem apagar');
  ok((await C1.file(`/portal/files/${vid}`)).status === 404, 'material retirado deixa de ser acessível ao cliente');
  ok((await C2.file(`/portal/files/${img1}`)).status === 404, 'outro cliente não acessa materiais publicados deste projeto');

  origLog('\nOrçamentos, comparativo e aprovações');
  const s1 = await A.post('/r/suppliers', { company: 'Marcenaria Alfa' }); const s2 = await A.post('/r/suppliers', { company: 'Marcenaria Beta' });
  let q1 = await A.post('/r/quotes', { project_id: p1.id, item: 'Marcenaria', supplier_id: s1.id, amount: 42000, deadline_days: 45, payment_terms: '50% + 50%', scope: 'Cozinha e dormitórios', included: 'Fabricação\nMontagem\nFrete', valid_until: D(20), client_notes: 'MDF Duratex' });
  const q2 = await A.post('/r/quotes', { project_id: p1.id, item: 'Marcenaria', supplier_id: s2.id, amount: 38000, included: 'Fabricação', excluded: 'Montagem\nFrete', notes: 'NOTA INTERNA margem' });
  const qInt = await A.post('/r/quotes', { project_id: p1.id, item: 'Iluminação', amount: 9000 });
  ov = await C1.get('/portal/overview'); ok(!ov.projects.find((x) => x.id === p1.id).quotes.length, 'orçamentos não liberados ficam ocultos');
  await A.put(`/r/quotes/${q1.id}`, { client_visible: 1 }); await A.put(`/r/quotes/${q2.id}`, { client_visible: 1 });
  const qf = (await (async () => { const fd = new FormData(); fd.append('files', new Blob([Buffer.from('%PDF-1.4 proposta')], { type: 'application/pdf' }), 'proposta-alfa.pdf'); fd.append('entity', 'quotes'); fd.append('entity_id', String(q1.id)); return A.upload('/files', fd); })()).ids[0];
  ov = await C1.get('/portal/overview'); pp = ov.projects.find((x) => x.id === p1.id);
  const g = pp.quotes.find((x) => x.item === 'Marcenaria');
  ok(g && g.options.length === 2 && !pp.quotes.find((x) => x.item === 'Iluminação'), 'somente orçamentos liberados aparecem, por categoria');
  const oa = g.options.find((o) => o.id === q1.id);
  ok(oa.scope === 'Cozinha e dormitórios' && oa.included.length === 3 && oa.payment_terms === '50% + 50%' && oa.valid_until && oa.files.length === 1, 'orçamento com escopo, itens, condições, validade e arquivo original');
  ok(!JSON.stringify(ov).includes('NOTA INTERNA'), 'observações internas não vão ao portal');
  ok((await C1.file(`/portal/files/${qf}`)).status === 200 && (await C2.file(`/portal/files/${qf}`)).status === 404, 'arquivo da proposta: acesso só do próprio cliente');
  ok(!('expenses' in ov) && !JSON.stringify(ov).includes('"balance"'), 'portal sem caixa nem despesas do escritório');

  const ap = await A.post(`/projects/${p1.id}/approvals`, { title: 'Escolha da marcenaria', kind: 'orcamento', quote_item: 'Marcenaria', reason: 'A escolha da marcenaria é necessária para iniciar a fabricação.', blocks_stage: 'Fabricação da marcenaria', due_date: D(7) });
  ov = await C1.get('/portal/overview'); pp = ov.projects.find((x) => x.id === p1.id);
  let pa = pp.approvals.find((x) => x.id === ap.id);
  ok(pa && pa.status === 'aberta' && pa.options.length === 2 && pa.reason && pa.blocks_stage === 'Fabricação da marcenaria', 'pendência visível com motivo, etapa e opções');
  ok(pp.updates.some((u) => u.sub === 'aprovacoes' && u.ref === `apr-${ap.id}`), 'últimas atualizações com acesso direto ao item');
  ok(!(await C2.get('/portal/overview')).projects.some((x) => x.approvals.some((a) => a.id === ap.id)), 'outro cliente não vê a pendência');
  await rejects(C2.post(`/portal/approvals/${ap.id}/decide`, { action: 'aprovada', quote_id: q1.id }), 404, 'outro cliente não consegue decidir');
  await rejects(C1.post(`/portal/approvals/${ap.id}/decide`, { action: 'aprovada' }), 400, 'com duas opções, é preciso escolher uma');
  await rejects(C1.post(`/portal/approvals/${ap.id}/decide`, { action: 'aprovada', quote_id: qInt.id }), 400, 'não aprova orçamento não liberado');
  await rejects(C1.post(`/portal/approvals/${ap.id}/decide`, { action: 'ajustes', comment: '' }), 400, 'ajuste exige comentário');
  await C1.post(`/portal/approvals/${ap.id}/decide`, { action: 'ajustes', comment: 'Incluir montagem na Beta' });
  ok(get('SELECT status FROM approvals WHERE id = ?', ap.id).status === 'ajustes', 'pedido de ajustes vira pendência do escritório');
  ok(get("SELECT COUNT(*) n FROM notifications WHERE kind = 'aprovacao_cliente' AND title LIKE 'Cliente pediu ajustes%'").n > 0, 'escritório notificado do pedido de ajustes');
  await A.post(`/approvals/${ap.id}/reopen`, { reason: 'Beta revisou o orçamento' });
  await C1.post(`/portal/approvals/${ap.id}/decide`, { action: 'aprovada', quote_id: q1.id });
  let row = get('SELECT * FROM approvals WHERE id = ?', ap.id);
  const ev = get("SELECT * FROM approval_events WHERE approval_id = ? AND action = 'aprovada' ORDER BY id DESC", ap.id);
  ok(row.status === 'aprovada' && row.decided_quote_id === q1.id && row.decided_version === 1, 'aprovação registrada com item e versão');
  ok(ev.actor === 'cliente' && ev.origin === 'portal' && ev.created_at && JSON.parse(ev.snapshot).supplier === 'Marcenaria Alfa' && JSON.parse(ev.snapshot).amount === 42000, 'registro com cliente, data/hora, fornecedor e valor');
  ok(get("SELECT COUNT(*) n FROM notifications WHERE kind = 'aprovacao_cliente' AND title LIKE 'Cliente aprovou%'").n > 0, 'escritório notificado da aprovação');
  const qq = get('SELECT * FROM quotes WHERE id = ?', q1.id);
  ok(qq.client_selected === 1 && qq.status !== 'contratado', 'aprovar não contrata o fornecedor');
  ok(!get("SELECT 1 FROM expenses WHERE description LIKE '%Marcenaria%'") && !get("SELECT 1 FROM incomes WHERE status = 'recebido'"), 'aprovar não registra pagamento');
  await rejects(C1.post(`/portal/approvals/${ap.id}/decide`, { action: 'aprovada', quote_id: q2.id }), 400, 'não aprova duas vezes a mesma pendência');

  origLog('\nRevisão de orçamento já aprovado');
  q1 = await A.put(`/r/quotes/${q1.id}`, { amount: 45000 });
  row = get('SELECT * FROM approvals WHERE id = ?', ap.id);
  ok(q1.version === 2 && row.status === 'aberta', 'valor mudou → versão 2 e nova aprovação solicitada');
  ok(get("SELECT 1 FROM approval_events WHERE approval_id = ? AND action = 'aprovada' AND quote_version = 1", ap.id), 'aprovação anterior preservada na versão original');
  await A.put(`/r/quotes/${q1.id}`, { client_notes: 'só observação' });
  ok(get('SELECT version FROM quotes WHERE id = ?', q1.id).version === 2, 'mudança que não altera valor/escopo não cria versão');

  origLog('\nDecisão registrada pelo escritório (WhatsApp, reunião…)');
  await rejects(A.post(`/approvals/${ap.id}/register`, { action: 'aprovada', quote_id: q1.id, confirmed_at: D(0) }), 400, 'origem obrigatória');
  await rejects(A.post(`/approvals/${ap.id}/register`, { action: 'aprovada', quote_id: q1.id, origin: 'whatsapp', confirmed_at: D(2) }), 400, 'data da confirmação não pode ser futura');
  const proof = (await up({ project_id: p1.id, category: 'Comprovantes de decisão' }, 'print.jpg')).ids[0];
  const reg = await A.post(`/approvals/${ap.id}/register`, { action: 'aprovada', quote_id: q1.id, origin: 'whatsapp', confirmed_at: D(-1), comment: 'Confirmou por mensagem', attachment_doc_id: proof });
  const ev2 = reg.events[reg.events.length - 1];
  ok(reg.status === 'aprovada' && ev2.actor === 'escritorio' && ev2.by === 'Irineu' && ev2.confirmed_at === D(-1) && ev2.quote_version === 2, 'registrado com usuário, data, origem e versão 2');
  ok(/Decisão registrada pelo escritório — confirmação recebida por WhatsApp/.test(ev2.label), 'histórico identifica que foi o escritório');
  ov = await C1.get('/portal/overview'); pa = ov.projects.find((x) => x.id === p1.id).approvals.find((x) => x.id === ap.id);
  ok(pa.status === 'aprovada' && pa.events.some((e) => e.by === 'Escritório' && /WhatsApp/.test(e.label)) && !pa.events.some((e) => e.attachment_doc_id), 'portal atualizado sem segunda confirmação, sem expor o comprovante');
  ok(get('SELECT client_visible FROM documents WHERE id = ?', proof).client_visible === 0, 'comprovante fica interno');
  await rejects(A.post(`/approvals/${ap.id}/register`, { action: 'aprovada', quote_id: q2.id, origin: 'reuniao', confirmed_at: D(0) }), 400, 'alterar decisão exige correção com motivo');
  await rejects(A.post(`/approvals/${ap.id}/register`, { action: 'aprovada', quote_id: q2.id, origin: 'reuniao', confirmed_at: D(0), corrects_event_id: ev2.id }), 400, 'correção sem motivo é recusada');
  const fix = await A.post(`/approvals/${ap.id}/register`, { action: 'aprovada', quote_id: q2.id, origin: 'reuniao', confirmed_at: D(0), corrects_event_id: ev2.id, reason: 'Cliente mudou de ideia na reunião' });
  const ev3 = fix.events[fix.events.length - 1];
  ok(fix.decided_quote_id === q2.id && ev3.corrects_event_id === ev2.id && /Correção/.test(ev3.label) && /mudou de ideia/.test(ev3.comment) && fix.events.some((e) => e.id === ev2.id), 'correção mantém o histórico, autor e motivo');

  origLog('\nOutros projetos e permissões');
  const ap2 = await A.post(`/projects/${p2.id}/approvals`, { title: 'Aprovar layout', kind: 'documento' });
  ok(!(await C1.get('/portal/overview')).projects.some((x) => x.approvals.some((a) => a.id === ap2.id)), 'pendência de outro cliente isolada');
  await rejects(C1.get(`/projects/${p1.id}/client-area`), 403, 'cliente não acessa os controles internos');
  const ca = await A.get(`/projects/${p1.id}/client-area`);
  ok(ca.approvals.length === 1 && ca.media.length >= 5 && ca.history.length >= 5, 'painel interno reúne pendências, materiais e histórico');
  const hid = await A.post(`/projects/${p1.id}/approvals`, { title: 'Interna', kind: 'outro', client_visible: 0 });
  ok(!(await C1.get('/portal/overview')).projects.find((x) => x.id === p1.id).approvals.some((a) => a.id === hid.id), 'pendência oculta não aparece ao cliente');
  await A.put(`/projects/${p1.id}/next-step`, { next_step: 'Projeto executivo', next_step_due: '' });
  pp = (await C1.get('/portal/overview')).projects.find((x) => x.id === p1.id);
  ok(pp.next.name === 'Projeto executivo' && !pp.next.due, 'próxima etapa sem prazo → “Prazo a definir” no portal');
  // legado: escolha direta de orçamento passa pelo histórico
  const q3 = await A.post('/r/quotes', { project_id: p1b.id, item: 'Pedras', amount: 5000, client_visible: 1 });
  await C1.post(`/portal/quotes/${q3.id}/select`);
  ok(get("SELECT 1 FROM approvals a JOIN approval_events e ON e.approval_id = a.id WHERE a.project_id = ? AND e.action = 'aprovada' AND e.quote_id = ?", p1b.id, q3.id), 'escolha direta (tela antiga) registrada no histórico de aprovações');

  server.close();
  origLog(`\n${pass} testes ok, ${failN} falha(s).`);
  process.exit(failN ? 1 : 0);
})().catch((e) => { origLog(e); process.exit(1); });
